name: Coverage Report

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  coverage-report:
    name: Detailed Coverage Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
        
    - name: Install Node.js dependencies
      run: npm ci
      
    - name: Install Python dependencies
      run: |
        cd tools/dict_importer
        python -m pip install --user -e ".[dev]"
        
    - name: Run Node.js tests with coverage
      run: |
        echo "Running Node.js tests with coverage..."
        npm run test:coverage
        
    - name: Run Python tests with coverage
      run: |
        cd tools/dict_importer
        echo "Running Python tests with coverage..."
        python -m pytest tests/ --cov=dict_importer --cov-report=xml --cov-report=html --cov-report=term-missing -v
        
    - name: Generate coverage summary
      run: |
        echo "=== Node.js Coverage Summary ==="
        cat coverage/coverage-summary.json || echo "No Node.js coverage summary found"
        echo ""
        echo "=== Python Coverage Summary ==="
        cd tools/dict_importer
        python -m pytest tests/ --cov=dict_importer --cov-report=term-missing --quiet || echo "No Python coverage summary available"
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/lcov.info,./tools/dict_importer/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
